### ISSUE TITLE
Feature: Title/Interpret

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#128]
Iv'e noticed that after Alucards request Interpret has been changed to Artist,
But perhaps its better to have Artist as a extra field.
Since its confusing for the user.

What i reccomend reverting artist to interpret and then altering the tables to have one more collumn which holds artist information, Then add that artist field to the submit page.

Since not all videos are music videos it makes a lot more sense.

Best Regards, 
Jeroen Mathon - Network Administrator of N0xy networks.

**Comment by jithatsonei** [comment]
they can be left blank for a reason, video source can just be filled out if theres no song

**Comment by jithatsonei** [comment]
after re reading this

interpret is a fancy word for Artist, and artist is more commonly known in america (it took me a bit to figure out what interpret meant, with @sirx having to teach me what it meant)

**Comment by belst** [comment]
Artist is more general. So we'll keep artist.
