### ISSUE TITLE
NSFW And SFW Features

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#137]
NSFW ( Not safe for work) SFW ( Safe for work)
A feature that you can consider to filter NSFW webms. Or you can add a warning saying its NSFW. Be able to look at w0bm at public places or at home without any NSFW webms popping up randomly and don't have to worry about having embarrassing moments. 

Options you could consider:
- Get multiple people to agree on what's NSFW and SFW.
- Let the uploader decide if its NSFW or SFW.
- Make some users mods to only change people webms seen as NSFW or SFW
- Guidelines to show what's NSFW and SFW
- Maybe add a image warning if its NSFW like this 
  ![waterfox_2016-09-06_09-01-26](https://cloud.githubusercontent.com/assets/22022660/18266087/d0ea799a-7410-11e6-84cd-7b69a888115c.jpg)
- Add a option if you don't wanna see the NSFW warning image or text to users
- Option to see both NSFW and SFW webms
- Short description of what content is in the NSFW webm to consider playing for the user
- Uploader and user mods can put up short description of the NSFW webm

**Comment by belst** [comment]
will be easily done when tagging is finished since u can just filter on certain tags then.

**Comment by sirx** [comment]
I like this idea.

I'd say go for it.

Extra addition:

- unregistered users will default only see sfw, but can optional turn off the filter (cookie based)

Also: We need to talk about what classifies as nsfw and what does not!

This is a very important point, cause opinions split there very fast.

But all in all. just do it ™

**Comment by ghost** [comment]
How is tagging going to work?
I see a bunch of comments with tags in them but that can't be it... right? :o

**Comment by belst** [comment]
no there will be an extra form below the comments for tagging

**Comment by belst** [comment]
Done with tagging. Please Tag NSFW videos as such and if u see a video mistakenly tagged as `sfw` report to an admin.
