### ISSUE TITLE
{tag} + ","

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#176]
Using a comma to complete a tag also additionally adds a comma for the next tag.

https://koyaanis.com/p/tagcomma.webm

**Comment by belst** [comment]
@jkhsjdhjs

**Comment by jkhsjdhjs** [comment]
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/456

fixed this issue as suggested in the bootstrap-tagsinput issue with 8e6c63a102f3977f9fa8492c93a5be87c1418106
