### ISSUE TITLE
filter 'nsfw' and 'sfw'

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#183]
Using the filters 'nsfw' and 'sfw' filters all videos out, which leads you to a 'Whoops, looks like something went wrong.' error page when visiting w0bm.com/

This can be manually fixed by going to any w0bm video manually like so: w0bm.com/1
This way you have access to your filter options again, you can remove 'nsfw' or 'sfw' or both, and use the site as you normally would.

Suggestion: Prevent users from having both 'nsfw' and 'sfw' filters or always redirect them to /1 because /1 is beyond of our realm of sfw and nsfw'ness

**Comment by sirx** [comment]
nsfw and sfw filtering is currently live.

As an unregistered user you can only see videos tagged with sfw, except for the categories where currently everything is visibile for everyone. But this is going to be patched in the future.

Can be closed
