### ISSUE TITLE
Long tags not shown properly

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#186]
Long tags are not shown properly (no newline). They are also not deletable because the "x" is not visible anymore.

**Comment by belst** [comment]
Solution Ideas:
- put the `x` to delete in front of the tag.
- add title to tags so full tag is shown on mouseover (add ellipsis on overflow)
- limit tag length to something shorter

**Comment by sirx** [comment]
This is already fixed.

Was a shitload of css.
