### ISSUE TITLE
url tags underlining unintuitive

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#187]
All tags are underlined, because they are supposed to be clickable to search the index. When a tag contains a link, that link will also underline, but not because it's a link to the url, but because you will search for it in the index. This is unintuitive.

My suggestion is: Make the underlining of tags that contain links blue and make it open the actual link as it is seen on screen.

https://koyaanis.com/p/tagunderlining.png

**Comment by belst** [comment]
read the rules for tagging please. https://w0bm.com/rules
