### ISSUE TITLE
comments overlay tags slightly on dpi scaled devices

### ISSUE THREAD

**Issue by GottZ** [w0bm/w0bm.com#197]
chrome @ macbook pro 13" retina 2015
![kapture 2016-10-28 at 0 32 42](https://cloud.githubusercontent.com/assets/559564/19788040/6c6ef356-9ca6-11e6-9ec8-212636406a43.gif)

**Comment by GottZ** [comment]
pff.. dann mach ichs halt selber..

**Comment by sirx** [comment]
> pff.. dann mach ichs halt selber..

:DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

Weihnachten gelle

**Comment by GottZ** [comment]
pff.. > mac os
