### ISSUE TITLE
Scrollbar at tag section?

### ISSUE THREAD

**Issue by Lym0nade** [w0bm/w0bm.com#235]
Reicht ja son kleiner Punkt der da rauf und runter geht.
Aber halt irgendwas, damit man sieht, jo, da kannste runterscrollen.

**Comment by sirx** [comment]
Die Scrollbar in der Tag Sektion ist mit Absicht ausgeblendet und wo bitte soll da denn noch Platz für einen "Punkt" oder ähnliches sein? In Chrome gehen die Tags bis an den Rand, sprich bis zu einer maximalen weite von 350px, da die Scrollbar ausgeblendet wird. In Firefox jedoch sieht man die Scrollbar durchgehend weil dieser Kackbrauser einfach nicht inzu Scrollbar CSS kann. Sei bitte spezifischer wo z.B. du dir einen Punkt vorstellen könntest und wie das ganze gemeint ist. Wäre ja auch eh nur Chrome only.

**Comment by Lym0nade** [comment]
Och Jungens, 
Die Scrollbar wieder einblenden, abspecken auf 10px
Der Balken, der anzeigt, auf welcher Höhe du dich gerade befindest wird zu einem simplen kleinen punkt umgestyled und fertig ist der shit
Wage mich mit meinen Skills vielleicht selber daran, aber jetzt ruft die Arbeit

**Comment by Lym0nade** [comment]
Natürlich alles transparent außer der Punkt
Juhu!

**Comment by sirx** [comment]
Abgelehnt. Scrollbar bleibt so wie sie ist. Nicht vorhanden.

**Comment by Lym0nade** [comment]
:)
Der Bereich für die Tags ist durch 2 türkise Linien hervorgehoben. Eine oberhalb, eine unterhalb.
Die untere: wech! (Erstmal)
Die wird Element vom Tag-Display, wird aber ganz nach unten gesetzt.
Das heißt nun also: Siehst du keine türkise Linie, weißt du, du kannst nach unten scrollen. Haste ganz nach unten gescrollt kommt die türkise Linie wieder zum hervorscheinen.
Und wenn man halt nicht nach unten scrollen kann, ist die türkise Linie wie gewohnt an Platz und Stelle.

**Comment by Lym0nade** [comment]
Merke gerade, dass die Tags in der 3. Zeile so halb rausgucken...

**Comment by sirx** [comment]
Die türkise Linie verhindert ja gerade dass die am unteren Rand rausgucken.
