### ISSUE TITLE
filter doesn't work while browsing inside of a category

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#238]
Example Title

**Comment by belst** [comment]
That is currently intended. We plan to change it though so that filters are applied everywhere

**Comment by ghost** [comment]
thank you for your honest answer. i will like your post

**Comment by belst** [comment]
Implemented in 6d5b657

**Comment by ghost** [comment]
OMG THANK YOU BELST XD

**Comment by Kim1338** [comment]
@mrhanky17 Lmao scheiß kdid erwerd erst mal 18 du dummer hsuol schlach dir um man 1 schlach du liechst komm offenbach

**Comment by sirx** [comment]
When not logged in and clickign on last to get the last webm in the category it jumps automatically to the first webm in the category also are last and first both displayed as the first webm in the category

**Comment by belst** [comment]
fixed with 45c21db
