### ISSUE TITLE
Ban time

### ISSUE THREAD

**Issue by cactushydrocodone** [w0bm/w0bm.com#239]
Hey,

If i want to ban a user, i get this dialog:
http://i.imgur.com/iUlvMGJ.png

Is this duration in seconds, minutes or hours?

It would be an enhancement to add a clarification about this in the dialog.

**Comment by Flummi** [comment]
-1 = permanent :_D

**Comment by jkhsjdhjs** [comment]
Append s for seconds, m for minutes and so on.
For example 1y2M15d16h5m3s would equal a ban time of 1 Year, 2 Months, 15 days, 16 hours, 5 minutes and 3 seconds. I think weeks (w) are also possible.

**Comment by cactushydrocodone** [comment]
Thank you very much hun
