### ISSUE TITLE
Feature Request: Deleted Videos Reason

### ISSUE THREAD

**Issue by cactushydrocodone** [w0bm/w0bm.com#241]
Wenn Video gelöscht wird, evt Kinderpornographie oder Illegale Inhalte, Grund auf Video Seite anzeigen, anstatt Link auf Startseite zu verweisen.

![image](https://user-images.githubusercontent.com/12892508/29411065-987caa76-8353-11e7-9f9b-1efa72a0aa00.png)

Wäre das was für w0bm? ist nur ein Vorschlag. Würde es transparenter machen finde ich :)

**Comment by sirx** [comment]
Also ich bin kein großer Fan dieser Idee, da es den Eindruck eines verfügbaren Videos erweckt, welches aber einfach nicht existiert und man einfach nur den Grund für die Entfernung sieht, ich fände es besser die Transparency Unterseite für diese Art Information zu benutzen und mehr Transparenz herzustellen.

**Comment by cactushydrocodone** [comment]
Kann man auch so machen, fände es einfach userfriendly wenn man bei einem Video, welches man z.b. sieht wenn man auf einen Link klickt von einem Freund, gerade sieht wieso es weg ist.

**Comment by sirx** [comment]
Dann ist ja alles klar, man verbleibt so und macht das vielleicht irgendwann mal.
