### ISSUE TITLE
Warnung vor abstoßenden Inhalten

### ISSUE THREAD

**Issue by sirx** [w0bm/w0bm.com#242]
Moderatoren sollen per one Klick die Möglichkeit haben eine Warnung vor bestimmte Videos zu schalten die besondern abgefuckt sind, diese Warnugn ist so groß wie der Video Container und beinhaltet einen Absatz in dem steht "Sind Sie sich sicher, dass Sie das folgende Video anschauen möchten? Ein Moderator markierte dieses Video als potentiell abstoßend und nicht für jeden geeignet, fahren Sie nur fort wenn sie über 18 sind oder wissen was Sie tun."

Dann gibts 2 Knöpfe. 1x Ich habe Eier 2x Ich will zu Mami

Ich habe Eier setzt einen Cookie der das Video freigibt und solange bestehen bleibt wie der Login Cookie, Button 2 ruft die Random Funktion auf und gibt ein Random sfw Video aus.

**Comment by Kim1338** [comment]
Warnung*

**Comment by sirx** [comment]
Hat sich erledigt!
