### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by lug-gh** [w0bm/w0bm.com#251]
When running `php artisan key:generate` I get this error: 

```
[RuntimeException]
  No supported encrypter found. The cipher and / or key length are invalid.

```

this is my .env file

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=***

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=***
MAIL_PORT=587
MAIL_USERNAME=***
MAIL_PASSWORD=***
MAIL_ENCRYPTION=tls

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
```

I installed all php extensions i could get, mcrypt is running and AES-256-CBC is enabled in php

**Comment by belst** [comment]
This is a problem with the way artisan generates the key.

It needs to have a key already, if u have `AES-256-CBC` enabled in the config you should simply provide random 32 character string, eg: `SomeRandomStringWith32Characters` which is 32 characters as `APP_KEY`. then u can simply `key:generate` and replace it with the newly generated key.

I do agree, this is a bit stupid and should possibly be fixed or automated. (It probably is already in newer laravel versions)

**Comment by lug-gh** [comment]
Thanks man!
As long as this isn't fixed, it should be mentioned in the installing instructions :)

**Comment by belst** [comment]
probably :D

**Comment by jkhsjdhjs** [comment]
Hey @lug-gh,
could you try reproducing this error, but instead of setting an app key in your .env, replacing `SomeRandomString` with `SomeRandomStringWith32Characters` in [line 81 of your config/app.php](https://github.com/w0bm/w0bm.com/blob/master/config/app.php#L81) and see if it fixes the problem too?

**Comment by lug-gh** [comment]
Yes, I can do that, need to reinstall it anyway, I just destroyed my installation 👎 

BTW: is there any other way to run this webserver, not by php artisan serve?
Because I'm running it on a linux server and are only able to reach it via reverse proxy, but thats not the best way to do I guess. (also I dont know the correct settings)
https://laravel.com/docs/5.5/deployment#server-configuration - did not work, blank page (no php errors )

**Comment by jkhsjdhjs** [comment]
Yes, you should be able to server it with any modern http server. Hmm, the configuration on the page you linked should work, we're using a similar configuration.
```nginx
root some_path/public;
index index.html index.htm index.php;

location / {
    try_files $uri $uri/ /index.php?$args;
}

location ~ \.php {
    fastcgi_pass unix:/run/php-fpm/php-fpm.sock; #path to your php-fpm socket may differ
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $request_filename;
    include fastcgi_params;
}
```

**Comment by lug-gh** [comment]
@jkhsjdhjs It works only if I also delete the line `APP_KEY=` from my .env and adding it back after `key:generate` with the key i got from that

And thanks, that nginx config works too!

**Comment by jkhsjdhjs** [comment]
Ah ok, I'll change the initial key in the app config then. Thanks!
