### ISSUE TITLE
Focus On FullScreen Button Doesn'T DisAppear When Clicking And Releasing

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#252]
Hello I Like CapitaLize So When You Click Fulscreen, Then Not Click Fulscreen, Then Focus Still There, So When Space To Pause, Video UnFulScreens. Pls Fix.
https://koyaanis.com/i/1518557139181.webm

**Comment by ghost** [comment]
https://koyaanis.com/i/1518557139181.webm

**Comment by ghost** [comment]
sry lool first time github ^^

**Comment by belst** [comment]
Duplicate of #247
