### ISSUE TITLE
fix mettscanner in irc @belst

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#256]
@belst  the irc mettscaner show random results but results are not random they show 50% then 2% wtf?

**Comment by sirx** [comment]
ze mettskänner is ze werry best eksampel of hau to meyk somwon mett
![flummisticker2](https://user-images.githubusercontent.com/14188379/37223793-e782377a-23d1-11e8-8d6e-f3a96bb96c97.png)

**Comment by GottZ** [comment]
such stooped. so wow.
