### ISSUE TITLE
all favorites suddenly not in order anymore

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#268]
who fucked this up? my favs are now completely scrambled

**Comment by belst** [comment]
favorites where never really ordered. they just happened to have the same order most of the time

**Comment by ghost** [comment]
favorites appeared as you added them.. last added favorite was last in list. now the list is completely fucked over

**Comment by belst** [comment]
That was never guaranteed though. It just happened to be that way because thats how databases work. But it wasn't defined so it could change anytime.

**Comment by ghost** [comment]
so my favorite order is forever gone and irrevocable???? great stuff love it.

**Comment by belst** [comment]
w0bm v2 will have this fixed. I think newly added favs should also be ordered.

**Comment by ghost** [comment]
so they will be back as they used to be `??

**Comment by sirx** [comment]
Beende dich Kim

**Comment by ghost** [comment]
nein
