### ISSUE TITLE
HTTPs inclusions

### ISSUE THREAD

**Issue by nikeee** [w0bm/w0bm.com#29]
When using HTTPS, the CSS and other media is still included via `http` and therefore isn't loaded properly:

``` html
<link rel="stylesheet" href="http://w0bm.com/css/style.css">
```

The easiest would be changing it to be protocol indepentent:

``` html
<link rel="stylesheet" href="//w0bm.com/css/style.css">
```

**Comment by belst** [comment]
even though https isnt even enabled anywhere, we include the css with laravels asset helper which uses the current scheme of the request:

http://laravel.com/docs/5.1/helpers#method-asset

**Comment by nikeee** [comment]
```
$ wget -qO- https://w0bm.com | grep "http://w0bm.com/css"
<link rel="stylesheet" href="http://w0bm.com/css/style.css">
```

The certificate is issued by cloudflare, so I am assuming that cloudflare wraps the SSL for you. I think cloudflare only caches HTTP requests of w0bm, without using TLS. This results in the server thinking the request came in via plain HTTP, but that isn't necessarily the case, meaning that laravel uses HTTP in its asset function.
This could be resolved by configuring HTTPS on the main server behind cloudflare (or by instructing laravel to be protocol independent when using asset(), which is not a bad idea anyways). I thi
nk you don't even need a valid certificate, since cloudflare wraps the stream with its own.
