### ISSUE TITLE
Ein paar Vorschläge

### ISSUE THREAD

**Issue by bkakatze** [w0bm/w0bm.com#35]
>Benachrichtigungen

+ Benachrichtigung bei einem Kommentar oder Highlight [@*]
+ Keine Privaten Nachrichten, dafür gibt es den IRC
+ Schriftverkehr nur Benutzer > Administrator/Moderator | Administrator/Moderator > Benutzer

>Editierfunktion

+ Bereits hochgeladene Uploads zusätzlich editieren können > Interpret, Titelname, Quelle, Kategorie
+ Von Nutzern nacheditierte Uploads werden in eine Warteschlange im Moderationsbereich geschoben und müssen genehmigt werden.

>Videos

+ Autoplay
+ Playlist
+ Kategorie Filter

**Comment by belstgut** [comment]
Bitte ein Vorschlag pro issues und hier sind auch viele Duplikate dabei
