### ISSUE TITLE
Titel/Beschreibung hinzufügen

### ISSUE THREAD

**Issue by Scarwolf** [w0bm/w0bm.com#39]
Für Leute mit einer langen Liste an Favoriten wäre es gut wenn WebMs betitelt werden müssen (Kurze Beschreibung des Inhalts) damit die Favoritenliste nicht mehr so aussieht:

![lel](http://i.imgur.com/WvW0hnr.png)

**Comment by GottZ** [comment]
dann schreib einfach zeug in die kommentare. sobald wir editierfunktionen eingebaut haben gehen wir eh noch mal alle videos zwecks tagging durch.
