### ISSUE TITLE
improving Video Player

### ISSUE THREAD

**Issue by GottZ** [w0bm/w0bm.com#79]
# make it superior
### sorry for the delay. will keep this updated.
- [x] seeking bar
- [x] buffering bar
- [x] time information
- [x] buttons
- [x] mobile support / simplificated interface
- [x] playback rate switch
- [x] volume bar
- [x] 1.0 volume on mobile devices
- [x] profit

**Comment by sirx** [comment]
Kannste schließen, Videoplayer (videojs) wurde implementiert.

**Comment by belst** [comment]
finished implementing videojs with 2d4f0789f0020ed86ec2d18919c564f23f67b34b
